name: Create Legacy Sigil for Windows

on:
  workflow_dispatch: 
    branches: master
    inputs:
      tag_name:
        description: 'Sigil tag to use'
        required: true
        default: ''

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: main

    - name: Checkout Sigil Tag
      uses: actions/checkout@v3
      with:
        repository: 'Sigil-Ebook/Sigil'
        ref: '${{ github.event.inputs.tag_name }}'
        path: 'sigil'
      
    - name: Get Sigil Windows source asset
      id: get_src_asset
      run: |
        $TAG = "${{ github.event.inputs.tag_name }}
        $URL = "https://github.com/Sigil-Ebook/Sigil/archive/refs/tags/$TAG.zip"
        Invoke-WebRequest $URL -OutFile 'Sigil-${{ github.event.inputs.tag_name }}.zip'
        $URL = "https://github.com/Sigil-Ebook/Sigil/releases/download/$TAG/Sigil-$TAG.zip.sig"
        Invoke-WebRequest $URL -OutFile 'Sigil-Sigil-$TAG.zip.sig'
      shell: pwsh

#    - name: Create Release
#      if: ${{ steps.check_tag_name.outputs.match != '' }}
#      uses: ncipollo/release-action@v1
#      with:
#        token: ${{ secrets.ROBO_ACTIONS }}
#        name: ${{ steps.create_archive.outputs.fname }}
#        tag: ${{ github.event.inputs.tag_name }}
#        body: |
#          Changes in this Release
#          - First Change
#          - Second Change
#        draft: true
#        prerelease: false
#        artifacts: "./${{ steps.create_archive.outputs.fname }}.tar.gz.sig, ./${{ steps.create_archive.outputs.fname }}.zip.sig"
