name: Create Legacy Sigil for Windows

on:
  workflow_dispatch: 
    branches: master
    inputs:
      tag_name:
        description: 'Sigil tag to use'
        required: true
        default: ''
env:
  BUILD_TYPE: Release
  VC: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC
  VARSALL: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
  TOOLCHAIN: 14.1
  ARCH: x86
  QT_MAJ_VER: 5
  QT: MyQtx86_WE\Qt5.12.9
  DOWNLOADQT: https://github.com/dougmassay/win-qtwebkit-5.212/releases/download/v5.212-1/MyQtx86_5.12.9_VS2017_WE.7z
  INNO: C:\Program Files (x86)\Inno Setup 6
  PY_VER: 3.8.3
  PYTHON: \hostedtoolcache\windows\Python\3.8.3\x86

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: 'main'

    - name: Checkout Sigil Tag
      uses: actions/checkout@v3
      with:
        repository: 'Sigil-Ebook/Sigil'
        ref: '${{ github.event.inputs.tag_name }}'
        path: 'sigil'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        architecture: ${{env.ARCH}}
        python-version: ${{env.PY_VER}}

    - name: Install pip dependencies
      working-directory: ${{GITHUB_WORKSPACE}}\main
      shell: cmd
      run: |
        set PATH=C:\%PYTHON%;C:\%PYTHON%\Scripts;%PATH%
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      
    - name: Get Sigil Windows source asset and sig
      id: get_src_asset
      run: |
        $TAG = "${{ github.event.inputs.tag_name }}"
        $URL = "https://github.com/Sigil-Ebook/Sigil/archive/refs/tags/$TAG.zip"
        Invoke-WebRequest $URL -OutFile 'Sigil-$TAG.zip'
        $URL = "https://github.com/Sigil-Ebook/Sigil/releases/download/$TAG/Sigil-$TAG.zip.sig"
        Invoke-WebRequest $URL -OutFile 'Sigil-Sigil-$TAG.zip.sig'
      shell: pwsh

    - name: Cache Custom Qt
      uses: actions/cache@v3
      with:
        path: ${{runner.workspace}}\${{env.QT}}
        key: ${{ runner.os }}-qtdeps-${{hashFiles('**/reset-win-caches.txt')}}
  
    - name: Install Custom Qt
      shell: cmd
      run: |
        if not exist ${{runner.workspace}}\%QT% cd ${{runner.workspace}} & curl -L -o webkit.7z "%DOWNLOADQT%" & 7z x webkit.7z -y
        if exist ${{runner.workspace}}\%QT%\bin cd ${{runner.workspace}}\%QT%\bin & echo [Paths] > qt.conf
        if exist ${{runner.workspace}}\%QT%\bin cd ${{runner.workspace}}\%QT%\bin & echo Prefix=.. >> qt.conf

    - uses: lukka/get-cmake@latest

    - name: Create Build Environment
      shell: cmd
      run: |
        set PATH=${{runner.workspace}}\%QT%\bin;%PATH%
        echo ${{runner.workspace}}
        mkdir ${{runner.workspace}}\build
        cd ${{runner.workspace}}\build
        qmake -v
        python --version

    - name: Build Sigil
      shell: cmd
      working-directory: ${{runner.workspace}}\build
      run: |
        set PATH=C:\%PYTHON%;${{runner.workspace}}\%QT%\bin;%PATH%
        call "%VARSALL%" %ARCH% -vcvars_ver=%TOOLCHAIN%
        cmake %GITHUB_WORKSPACE%\sigil ^
        -G "Ninja" ^
        -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
        -DTRY_NEWER_FINDPYTHON3=1 ^
        -DPYTHON3_LIBRARIES="C:\%PYTHON%\libs\python38.lib" ^
        -DPYTHON3_INCLUDE_DIRS="C:\%PYTHON%\include" ^
        -DPYTHON3_EXECUTABLE="C:\%PYTHON%\python.exe" ^
        -DBUILD_FOR_WIN7=1 ^
        -DQt%QT_MAJ_VER%_DIR="${{runner.workspace}}\$QT\lib\cmake\Qt%QT_MAJ_VER%"
        ninja -j2

    - name: Build Installer
      shell: cmd
      working-directory: ${{runner.workspace}}\build
      run: |
        set PATH=C:\%PYTHON%;%INNO%;${{runner.workspace}}\%QT%\bin;%PATH%
        set /p RedistVersion=<"%VC%\Auxiliary\Build\Microsoft.VCRedistVersion.default.txt"
        set REDIST=%VC%\Redist\MSVC\%RedistVersion%\vc_redist.%ARCH%.exe
        echo "%REDIST%"
        cp '%REDIST%' %GITHUB_WORKSPACE%\sigil\installer\vcredist_%ARCH%.exe
        call "%VARSALL%" %ARCH% -vcvars_ver=%TOOLCHAIN%
        ninja -j2 makeinstaller

    - uses: actions/upload-artifact@v3
      with:
        name: sigil-installer
        path: ${{runner.workspace}}\build\installer\*.exe
        retention-days: 3

#    - name: Create Release
#      if: ${{ steps.check_tag_name.outputs.match != '' }}
#      uses: ncipollo/release-action@v1
#      with:
#        token: ${{ secrets.ROBO_ACTIONS }}
#        name: ${{ steps.create_archive.outputs.fname }}
#        tag: ${{ github.event.inputs.tag_name }}
#        body: |
#          Changes in this Release
#          - First Change
#          - Second Change
#        draft: true
#        prerelease: false
#        artifacts: "./${{ steps.create_archive.outputs.fname }}.tar.gz.sig, ./${{ steps.create_archive.outputs.fname }}.zip.sig"
